#!/bin/bash
# Create CommonJS package.json
cat >dist/cjs/package.json <<JSON
{
    "type": "commonjs",
    "types": "../types/index.d.ts",
    "browser": {
        "./index.js": "./browser.js",
		"./server/index.js": "./server/browser.js",
        "./database/services/sandbox/index.ts": "./database/services/sandbox/browser.js",
        "./app/settings/index.js": "./app/settings/browser.js",
		"./app/verifyStorage/index.js": "./app/verifyStorage/browser.js",
		"./controller/storage/index.js": "./controller/storage/browser.js",
        "./controller/request/index.js": "./controller/request/browser.js",
        "./utils/base64/index.js": "./utils/base64/browser.js",
        "./utils/localStorage/index.js": "./utils/localStorage/browser.js"
    }
}
JSON
# Write typings to support Node16 module resolution 
cat >dist/cjs/index.d.ts <<TYPESCRIPT
export * from '../types/index.js';
TYPESCRIPT
# Create ESM package.json
cat >dist/esm/package.json <<JSON
{
    "type": "module",
    "types": "../types/index.d.ts",
    "browser": {
        "./index.js": "./browser.js",
		"./server/index.js": "./server/browser.js",
        "./database/services/sandbox/index.ts": "./database/services/sandbox/browser.js",
        "./app/settings/index.js": "./app/settings/browser.js",
		"./app/verifyStorage/index.js": "./app/verifyStorage/browser.js",
		"./controller/storage/index.js": "./controller/storage/browser.js",
        "./controller/request/index.js": "./controller/request/browser.js",
        "./utils/base64/index.js": "./utils/base64/browser.js",
        "./utils/localStorage/index.js": "./utils/localStorage/browser.js"
    }
}
JSON
# Write typings to support Node16 module resolution 
cat >dist/esm/index.d.ts <<TYPESCRIPT
export * from '../types/index.js';
TYPESCRIPT
# Prepend ts-ignore for imported Observable in types
cat >dist/types/optional-observable.d.ts <<TYPESCRIPT
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: rxjs dependency is optional and only needed when using methods that require them
TYPESCRIPT
#